### ISSUE TITLE
デバイス規制を回避する実装がなされていない

### ISSUE THREAD

**Issue by raibonn** [xpadev-net/niconicomments-convert#113]
デバイス規制を回避する実装が行われていないため，認証を行ったとしてもダウンロードできない動画等がある
[Log]
```
[2024-12-14 02:05:32.323] [error] [ipcManager] failed to process ipc message ipcMessage: {
  type: 'getNiconicoMovieMetadata',
  nicoId: 'sm44370093',
  host: 'controller'
} error: Error: failed to get metadata
{
	"meta": {
		"status": 400,
		"errorCode": "FORBIDDEN"
	},
	"data": {
		"reasonCode": "HARMFUL_VIDEO"
	}
}
    at getV3GuestMetadata (C:\Users\<Username>\Downloads\niconicomments-convert-0.0.27-win\resources\app.asar\build\electron\lib\niconico\utils.js:50:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\<Username>\Downloads\niconicomments-convert-0.0.27-win\resources\app.asar\build\electron\ipc-manager.js:57:24
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86542)
```
[YT-DLP内の回避実装](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/niconico.py)などを参考にしてすべての動画から取得を可能にすることを提案します。

**Comment by xpadev-net** [comment]
従来使用していた v3 API を Watch Page API に置き換えたので取得自体はできるようになりました
次回リリース時に反映予定です
